### ISSUE TITLE
Layout of IP blocks

### ISSUE THREAD

**Issue by Ahmedredamohamed2022** [christoph-weiser/mpw7#1]
Hello, 
I hope my message finds you well.
I am writing to you if you can please provide us with the layout of each IP block (*.mag), individually.  
such as:  
Bandgap reference.
linear regulators, 1.2V and 1.5V.
Clock generator.
Bias current/voltage generator.
10-bit SAR-ADC
Test buffer with multiplexer input.
"https://github.com/christoph-weiser/mpw7"

I am waiting for your kind reply
thanks
Ahmed Reda

**Comment by christoph-weiser** [comment]
You'll find a file called design.gds.gz ([design.gds.gz](https://github.com/christoph-weiser/mpw7/blob/7d5b22818e6880276f84ce850211723f0d270da0/gds/design.gds.gz)) in the gds folder of this repository.

 That file is hierachical, so if you open it in klayout you can simply right click on the block of interest and "Save Selected Cells As" to save any of the blocks as individual gds or mag files.

**Comment by Ahmedredamohamed2022** [comment]
Thank you for you reply . I have two more inquiries .
Can i read  your gds file using MAGIC, please?
or do you have the layout of the IP blocks as *.mag?

**Comment by christoph-weiser** [comment]
Yes just decompress the design.gds.gz and open it with magic. You can also use the cell manager in magic to load the cells of interest and then save the cell as a new gds or mag file.

``` 
gunzip design.gds.gz
magic design.gds
```

**Comment by Ahmedredamohamed2022** [comment]
Thank you .  Excuse me I have one more question.  did you have a documentation for each designed IP block including simulation results? can you share it with me please?

**Comment by christoph-weiser** [comment]
I have thus far not created any detailed result documentation. You will however find all the required testbenches to evaluate the performance of each block for yourself.
