### ISSUE TITLE
Bandgap cell

### ISSUE THREAD

**Issue by Ahmedredamohamed2022** [christoph-weiser/mpw7#2]
Hello,
I hope my message finds you well.
I am writing to you because i got an error when simulating the bandgap as shown. 
Here, I want to describe what i did 
1-I generated bandgap_lvs.spice  from bandgap.gds
2- I used bandgap_tb_tc.spice with bandgap_lvs.spice
3- I opened a terminal and wrote ngspice bandgap_tb_tc.spice and found the shown error.
can you help me to fix this error.
![issue](https://user-images.githubusercontent.com/105387946/202927164-18eb2596-f731-431f-abce-8d40ce7c4951.png)
bandgap_lvs.spice , bandgap.gds, and bandgap_tb_tc.spice  are attached in the next link
 `https://github.com/Ahmedredamohamed2022/Manual_Lab`

**Comment by christoph-weiser** [comment]
You missed to include the subckt definition of the pnp device. 
I think the required file from the pdk is found in models/all.spice

**Comment by Ahmedredamohamed2022** [comment]
I would like to inform you that, i simulated the schematic circuit successfully. However, when I generated the bandgap_lvs.spice from the layout and re-simulate the testbench again , i found this error. 
Is there any other file should i add to simulate the bandgap_lvs.spice !

**Comment by christoph-weiser** [comment]
Ok. In that case I think I know what is going on. The tool will extract a circuit that is different than the one in the PDK. . So check what pins the pnp device has in the PDK. Then check how the device is extracted with magic. There is even a tutorial on [youtube](https://www.youtube.com/watch?v=U4ox29-Oauw) on this topic. I also made a script to fix this problem you find it in my [ic_tools](https://github.com/christoph-weiser/ic_tools) repo.

**Comment by Ahmedredamohamed2022** [comment]
yeah, I got it. Thank you for your patience
Here, I simulated the extracted  spice from the layout and adjust the pnp terminals.  However, I get a difference between the pre-layout and post layout simulation. Does it mean  the extracted spice file is not correct.
Extracted spice file is attached here <https://github.com/Ahmedredamohamed2022/Manual_Lab>
![Picture1](https://user-images.githubusercontent.com/105387946/203186792-5fb5f96f-f03c-466f-a963-28a1eff8c07a.png)

**Comment by Ahmedredamohamed2022** [comment]
Hi, I found why the simulation result of extracted spice is not matched with the post-layout simulation result.  When doing LVS
 check , the  Netlists do not match, as shown. Do you think there is a wire in the layout is not connected as a schematic, right!
 or i do not have the last version of the layout.
![image](https://user-images.githubusercontent.com/105387946/203546764-fb015cf7-68f1-4b49-8332-e0bb5153e5bd.png)

**Comment by Ahmedredamohamed2022** [comment]
![image](https://user-images.githubusercontent.com/105387946/203577743-7f549dda-c341-4eee-a1d2-89a0b142c9d3.png)

**Comment by Ahmedredamohamed2022** [comment]
![image](https://user-images.githubusercontent.com/105387946/203577926-5e44d891-cbb7-4d1e-b692-a4f545467568.png)

**Comment by Ahmedredamohamed2022** [comment]
![image](https://user-images.githubusercontent.com/105387946/203584708-4bd487f7-03a3-43d6-b145-3df6c36fda2f.png)

**Comment by Ahmedredamohamed2022** [comment]
both gates have the same label/port!  is it right!!

**Comment by christoph-weiser** [comment]
Yes you are right. You can open the layout one level up in the hierarchy to see, which pin is which, since the naming is correct there. I don't see the issue, because remove labels of subblocks before I run lvs.

**Comment by Ahmedredamohamed2022** [comment]
Is there a way to remove labels of subblocks to run lvs! please

**Comment by christoph-weiser** [comment]
Yes in my [ic_tools](https://github.com/christoph-weiser/ic_tools) package you find a script called "assemble". It builds on some of the other scripts in the repository and will do that. If you want to create your own custom setup i suggest looking at the "labelremove" and "labelextract" scripts also found in the repository.

**Comment by Ahmedredamohamed2022** [comment]
Thanks. Excuse me what does it mean this error!
![image](https://user-images.githubusercontent.com/105387946/203642201-5b87f7a3-c157-459a-902c-f144a3807e28.png)

**Comment by christoph-weiser** [comment]
The first picture tells you that in Circuit 1 two sky130_fd_pr__pnp_05v5 devices have a connection from vss to the second node of the subckt. In Circuit 2: here are also two connections from vss to the second node of the subckt. However there are also additional two connections from vss to the first node of the subckt.

The second picture then tells you that there are connetions found in one netlist that cannot be found in the other. It also states that this is regarding the first port of sky130_fd_pr__pnp_05v5. It assigns this net a automatic name called a_26_26. 

These lvs errors can be difficult to debug, but it looks like you have shorted port 1 and port 2 in the circuit 2, which is not the case in circuit 1.

**Comment by Ahmedredamohamed2022** [comment]
yeah, I got it. Thank you for your guidance.
