### ISSUE TITLE
Analog and Digital LDO

### ISSUE THREAD

**Issue by Ahmedredamohamed2022** [christoph-weiser/mpw7#3]
Hi, I am writing to ask what is the different between the analog and digital LDO!
I think both LDOs have the same structure, right!
but, how I can get 1.2 V and 1.5 V from both!

![image](https://user-images.githubusercontent.com/105387946/204311300-74a3aa0d-ee64-48e5-984f-8bf5b5121df7.png)

**Comment by christoph-weiser** [comment]
Hi, yes they are indeed identical. The difference is the reference voltage applied to the LDO. The output voltage of the LDO is 2x the reference voltage applied to the vref pin.

**Comment by Ahmedredamohamed2022** [comment]
Thank you for kind reply. I   have one more question, please.  i want to know what is the maximum load current of LDO?
do you have the electrical characterization parameters of the LDO which includes load/line regulation, max/min load current, efficiency, dropout voltage, ...?
