### ISSUE TITLE
LDO and Bandgap at Vdd of 3.3V!

### ISSUE THREAD

**Issue by Ahmedredamohamed2022** [christoph-weiser/mpw7#4]
Hello, I am writing to double-check if the design of the LDO and bandgap circuits can operate at a Vdd of 3.3V. 
By the way, the simulation testbench did not complain when i simulate the LDO and bandgap circuits with Vdd of 3.3V
Is it OK? can I rely on the simulation results, for now?
what do you think?
Thanks

**Comment by christoph-weiser** [comment]
No i would not suggest that. The devices used in the circuit are nfet_01v8 and pfet_01v8, which means that you should not use them with 3.3V. But perhaps you can modify the circuit to operate with the nfet_03v3, pfet_03v3 devices.
